name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          npm run export
          git checkout --orphan gh-pages
          git --work-tree out add --all
          git --work-tree out commit -m "GitHub Pages deployment"
          git branch -D gh-pages
          git push origin --force gh-pages:gh-pages
